on:
  workflow_dispatch: # Manually running a workflow
  push:
    branches:
      - release/*
  pull_request:
    branches:
      - master

name: macOS build
jobs:
  test-macOS:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.py }})
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: macOS-latest, py: "3.9" }
    env:
      SDKROOT: /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
    steps:
      - name: CHECKOUT CODE
        uses: actions/checkout@v2
      - name: Cache pip
        uses: actions/cache@v2
        if: startsWith(runner.os, 'macOS')
        with:
          path: ~/Library/Caches/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Cache huggingface models
        uses: actions/cache@v2
        with:
          path: ~/.cache/huggingface
          key: ${{ runner.os }}-huggingface-
      - name: Cache imgocr models
        uses: actions/cache@v2
        with:
          path: ~/.imgocr
          key: ${{ runner.os }}-imgocr-
      - name: SETUP PYTHON
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.config.py }}
      - name: Install torch
        run: |
          python -m pip install --upgrade pip
          pip install Cython
          pip install torch
      - name: Install from pypi
        run: |
          pip install -U imgocr
          python -c "import imgocr; print(imgocr.__version__)"
          pip uninstall -y imgocr
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install .